# fly.toml app configuration file generated for 06-webserver-wild-tree-5255 on 2025-09-19T00:05:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '06-webserver-wild-tree-5255'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
